
import java.net.URL;
import java.util.Map;

import javax.xml.namespace.QName;
import javax.xml.ws.BindingProvider;

import org.apache.cxf.ws.addressing.AddressingProperties;
import org.apache.cxf.ws.addressing.AttributedURIType;
import org.apache.cxf.ws.addressing.EndpointReferenceType;
import org.apache.cxf.ws.addressing.JAXWSAConstants;
import org.apache.cxf.ws.addressing.WSAddressingFeature;

/**
 * This class was generated by Apache CXF 3.4.0
 * 2020-09-08T16:48:57.884-04:00
 * Generated source version: 3.4.0
 *
 */
public final class Client_Stub_Client {

    private static final QName SERVICE_NAME = new QName("http://ehealth.gov.on.ca/restful", "GeneralFhirService");

    private Client_Stub_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
    	
        URL wsdlURL = new URL("http://127.0.0.1:8080/soapmock?wsdl");
        GeneralFhirService fhirService = new GeneralFhirService(wsdlURL, SERVICE_NAME);
        
        GeneralFhirPortType servicePort = fhirService.getGeneralFhirDefaultPort(new WSAddressingFeature());

        AddressingProperties maps = new AddressingProperties();
        EndpointReferenceType ref = new EndpointReferenceType();
        AttributedURIType add = new AttributedURIType();
        add.setValue("http://www.w3.org/2005/08/addressing/anonymous");
        ref.setAddress(add);
        maps.setReplyTo(ref);
        maps.setFaultTo(ref);
        
        Map<String, Object> requestContext = ((BindingProvider)servicePort).getRequestContext();
        requestContext.put(JAXWSAConstants.CLIENT_ADDRESSING_PROPERTIES, maps);
        
//        AddressingProperties maps = new AddressingProperties();
//        EndpointReferenceType ref = new EndpointReferenceType();
//        AttributedURIType add = new AttributedURIType();
//        add.setValue("http://localhost:9090/decoupled_endpoint");
//        ref.setAddress(add);
//        maps.setReplyTo(ref);
//        maps.setFaultTo(ref);
//         
//        ((BindingProvider)servicePort).getRequestContext().put("javax.xml.ws.addressing.context", maps);        

        
//        List<org.apache.cxf.headers.Header> headers = new ArrayList<org.apache.cxf.headers.Header>();
//        org.apache.cxf.headers.Header dummyHeader = new org.apache.cxf.headers.Header(new QName("uri:org.apache.cxf", "dummy"), "decapitated",
//                                        new JAXBDataBinding(String.class));
//        headers.add(dummyHeader);         
//        //client side:
//        ((BindingProvider)servicePort).getRequestContext().put(org.apache.cxf.headers.Header.HEADER_LIST, headers);
        
        

        System.out.println("Invoking generalFhirOperation...");
       
        RestfulRequest request = RequestBuilder.createRestfulRequest();
		
		
        RestfulResponse response = servicePort.generalFhirOperation(request);
        System.out.println("generalFhirOperation.result=" + response);


        System.exit(0);
    }


}
